import fs from 'node:fs';
import assert from 'node:assert/strict';
import {launch,seed,accessibility,widths,artifacts,baseURL} from './support.mjs';
const browser=await launch();
try{
const {context,page}=await seed(browser);
const errors=[],results=[],a11y=[];page.on('pageerror',error=>errors.push(error.message));
 const check=async(name)=>{const m=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(m.scroll<=m.width+1,name+' page overflow');const dialog=page.locator('dialog[open]').last();if(await dialog.count()){const previous=page.viewportSize();for(const width of widths) { await page.setViewportSize({width,height:850}); const box=await dialog.boundingBox();assert(box.width<=width+1,name+' dialog overflow at '+width);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' overflow at '+width);if(name==='registration mobile'||name==='payment mobile')await page.screenshot({path:artifacts+'/'+name.split(' ')[0]+'-'+width+'.png'}); } await page.setViewportSize(previous);}results.push(name);};
 const axe=async(name)=>{const result=await accessibility(page,name);a11y.push(result);assert.equal(result.violations.length,0,JSON.stringify(result));};
 const escape=async()=>{await page.keyboard.press('Escape');await page.waitForTimeout(100);};
 await page.goto(`${baseURL}/`);await page.locator('.dashboard-view').waitFor();await check('dashboard');await axe('dashboard');
 await page.getByRole('button',{name:'Nouvel abonné',exact:true}).click();await page.locator('dialog[open]').waitFor();await check('registration mobile');await page.screenshot({path:artifacts+'/register-375.png'});await axe('registration');
 // Native dialogs keep focus inside after repeated keyboard traversal.
 for(let i=0;i<25;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement.closest('dialog')!==null),'focus escaped dialog');}
 await page.locator('#RegisterClientModal-field-0').fill('QA Nadia Test');await page.locator('#RegisterClientModal-field-1').fill('0663456789');await page.getByRole('button',{name:'Continuer vers la facturation',exact:true}).click();await page.locator('dialog form button[type=submit]').click();await page.locator('dialog[open]').waitFor({state:'detached'});assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('youness_wisp_clients')).some(c=>c.name==='QA Nadia Test')));results.push('subscriber registration');
 await page.locator('.page-heading').getByRole('button',{name:'Encaisser',exact:true}).click();await page.locator('dialog[open]').waitFor();await check('payment mobile');await axe('payment');await page.screenshot({path:artifacts+'/payment-375.png'});await page.locator('dialog select').first().selectOption('qa-client-2');await page.locator('dialog form button[type=submit]').click();await page.locator('#receipt-print-section').waitFor();await check('receipt');await page.screenshot({path:artifacts+'/receipt-375.png'});await page.emulateMedia({media:'print'});await page.setViewportSize({width:794,height:1123});await page.pdf({path:artifacts+'/receipt.pdf',format:'A4',printBackground:true});await page.screenshot({path:artifacts+'/receipt-print.png',fullPage:true});await page.emulateMedia({media:'screen'});await page.setViewportSize({width:375,height:850});await escape();results.push('payment and receipt');
 await page.locator('.nav-item:visible').nth(1).click();await page.locator('.directory-view').waitFor();await page.locator('#client-directory-search-input').fill('Salma');await page.waitForTimeout(300);assert.equal(await page.locator('.client-table tbody tr').count(),1);results.push('subscriber search');
 await page.getByRole('button',{name:'Salma El Amrani',exact:true}).click();await page.locator('dialog[open]').waitFor();await check('subscriber detail');await page.screenshot({path:artifacts+'/detail-375.png'});await axe('subscriber detail');await escape();
 await page.locator('.client-table button[title]').filter({has:page.locator('svg.lucide-pencil')}).click();await page.locator('dialog[open]').waitFor();await check('subscriber edit');await escape();
 await page.locator('.client-table button[title]').filter({has:page.locator('svg.lucide-message-square')}).click();await page.locator('dialog[open]').waitFor();await check('WhatsApp preview');await escape();
 await page.locator('.nav-item:visible').nth(2).click();await page.locator('.tickets-view').waitFor();await check('ticket board');await axe('ticket board');await page.getByRole('button',{name:'Créer un Ticket Incident',exact:true}).click();await page.locator('dialog[open]').waitFor();await check('new ticket');await page.screenshot({path:artifacts+'/ticket-modal-375.png'});await axe('new ticket');await page.locator('dialog textarea').fill('QA : vérifier le routeur.');await page.locator('dialog button[type=submit]').click();await page.locator('dialog[open]').waitFor({state:'detached'});results.push('ticket creation');
 await page.getByRole('button',{name:'Marquer comme résolu',exact:true}).first().click();await page.locator('dialog[open]').waitFor();await check('ticket resolution');await page.locator('dialog textarea').fill('QA : routeur vérifié.');await page.locator('dialog').getByRole('button',{name:'Enregistrer',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'detached'});results.push('ticket resolution saved');
 await page.getByRole('button',{name:'Liste',exact:true}).click();await check('ticket list');
 await page.locator('.nav-item:visible').nth(3).click();await page.locator('.team-view').waitFor();await axe('team');await page.getByRole('button',{name:'Ajouter un membre',exact:true}).click();await page.locator('dialog[open]').waitFor();await check('add member dialog');await page.screenshot({path:artifacts+'/team-modal-375.png'});await axe('add member');await escape();
 for(const title of ['Modifier les informations','Changer / Réinitialiser le mot de passe','Supprimer ce compte']){await page.locator('button[title="'+title+'"]').last().click();await page.locator('dialog[open]').waitFor();await check('team '+title);await escape();}
 // Theme and language remain reachable on small phones through preferences.
 await page.getByRole('button',{name:'Changer de thème',exact:true}).click();assert(await page.locator('html').evaluate(e=>e.classList.contains('dark')));await page.waitForTimeout(400);await page.screenshot({path:artifacts+'/team-dark-375.png'});await axe('dark team');
 await page.locator('.toolbar-actions > .icon-button').click();await page.locator('dialog[open]').waitFor();await check('preferences');await page.locator('dialog').getByRole('button',{name:'عربي',exact:true}).click();await escape();assert.equal(await page.locator('html').getAttribute('dir'),'rtl');await page.screenshot({path:artifacts+'/team-ar-375.png'});await check('Arabic RTL');
 await page.locator('.nav-item:visible').nth(0).click();await page.locator('.dashboard-view').waitFor();await page.screenshot({path:artifacts+'/dashboard-ar-dark-375.png'});await axe('Arabic dashboard');
 await page.setViewportSize({width:768,height:900});await page.screenshot({path:artifacts+'/dashboard-ar-dark-768.png'});await check('Arabic tablet');
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:artifacts+'/dashboard-ar-dark-1440.png'});await check('Arabic desktop');
 await page.setViewportSize({width:720,height:500});await check('200 percent browser zoom reflow equivalent');await page.screenshot({path:artifacts+'/zoom-reflow.png'});
 await page.goto(`${baseURL}/technician`);await page.locator('.field-workspace').waitFor();await page.setViewportSize({width:320,height:850});await check('field 320');await axe('field');await page.screenshot({path:artifacts+'/field-ar-dark-320.png'});
 await context.close();
 const loginContext=await browser.newContext();loginContext.setDefaultTimeout(15000);const login=await loginContext.newPage();await login.goto(`${baseURL}/login`);await login.locator('#login-identifier').waitFor();for(const width of [320,375,430,768,1024,1280,1440,1920]){await login.setViewportSize({width,height:900});assert(await login.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'login overflow '+width);}await login.setViewportSize({width:375,height:900});await login.screenshot({path:artifacts+'/login-375.png'});results.push('login eight widths');
 await login.locator('#login-identifier').fill('qa-invalid');await login.locator('#login-password').fill('invalid');await login.getByRole('button',{name:'Se connecter',exact:true}).click();await login.locator('#login-error').waitFor();results.push('login validation');
 await fs.promises.writeFile(artifacts+'/workflows.json',JSON.stringify({results,errors,a11y},null,2));console.log(JSON.stringify({results,errors,a11y:a11y.map(r=>({name:r.name,violations:r.violations.map(v=>v.id)}))}));assert.equal(errors.length,0,JSON.stringify(errors));

}catch(error){await fs.promises.writeFile(artifacts+'/workflows.json',JSON.stringify({failure:error.message},null,2));throw error;}finally{await browser.close();}
